services:
  django:
    build:
      context: ..
      dockerfile: docker/django/Dockerfile
    ports:
      - ${DJANGO_PORT}:8000
    environment:
      - DB_DEFAULT_HOST=postgresql
      - DB_DEFAULT_PORT=${POSTGRES_PORT}
      - DB_DEFAULT_USER=${POSTGRES_USER}
      - DB_DEFAULT_PASS=${POSTGRES_PASS}
      - DB_DEFAULT_NAME=${POSTGRES_NAME}
    volumes:
      - ../src:/src
    command: bash -c "python manage.py wait_for_db && \
                      python manage.py migrate && \
                      python manage.py runserver 0.0.0.0:8000"
    restart: always

  postgresql:
    image: postgres:17.6
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    restart: always
